#!/usr/bin/env bash
#
# c720-zram - Setup Zram on the Acer C720 with 4GB of RAM

set -euo pipefail

sudo apt install systemd-zram-generator -y

sudo tee /etc/systemd/zram-generator.conf >/dev/null <<'EOF'
[zram0]
zram-size = ram * 1.5
compression-algorithm = zstd
EOF

sudo systemctl daemon-reload && \
sudo systemctl start /dev/zram0

sudo tee /etc/sysctl.d/99-zram.conf >/dev/null <<'EOF'
vm.swappiness = 180
vm.vfs_cache_pressure = 50
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
vm.page-cluster = 0
EOF

sudo sysctl --system
