#!/usr/bin/env bash

# Reports all available hardware temperatures in Ubuntu. No additional software required.

base='/sys/class/hwmon/'

for hwmon_path in "${base}"*/; do
  hwmon=$(basename "${hwmon_path%/}")
  tempFiles="${hwmon_path}temp*_input"
  if compgen -G "${tempFiles}" >/dev/null; then
    echo
    echo "${hwmon} $(cat "${hwmon_path}name")"
    for temp in "${hwmon_path}"temp*_input; do
      tempNum=$(echo "${temp}" | awk -F'/' '{print $6}' | awk -F'_' '{print $1}')
      echo "    ${tempNum}: $(cat "${temp}" | awk '{print $1/1000}')°C"
    done
  fi
done

echo -e "\nTop 5 CPU Hogs:"
top -b -n 1 | head -n 12 | tail -n 6
echo
