#!/usr/bin/env bash

# Sync a fork with its upstream repository

if ! inGitDir; then
  echo "This script must be run in a git repository."
  exit 1
fi

# Checkout main
git checkout main && \
# Fetch and merge updates from origin
git pull && \
# Fetch upstream updates
git fetch upstream && \
# Merge upstream
git merge -m "Sync with upstream" upstream/main && \
# Push changes back to origin
git push origin
