#!/usr/bin/env bash

# Reports the named HDD's temperature.
# Usage: hddTemp sda

TP=`/usr/sbin/smartctl -A /dev/$1 | grep Temp -m 1 | awk -F " " '{printf "%d",$10}'`

if [ -z $2 ]; then
  echo $TP
fi

exit $TP
