#!/usr/bin/env bash
#
# install-firefox - Install Firefox from the Mozilla apt repo
#                   and block the snap version.
#
set -euo pipefail

install-firefox-prepare

sudo apt update && sudo apt install firefox
