#!/usr/bin/env bash

# Install composer and common packages

EXPECTED_SIGNATURE=$(wget https://composer.github.io/installer.sig -O - -q)
php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', '/tmp/composer-setup.php');")

if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]
then
  sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin/ --filename=composer
  RESULT=$?
  rm /tmp/composer-setup.php
  composer global require monolog/monolog
  composer global require bramus/monolog-colored-line-formatter
  composer global require aensley/media-organizer
  exit $RESULT
else
  >&2 echo 'ERROR: Invalid installer signature'
  rm /tmp/composer-setup.php
  exit 1
fi
