#!/usr/bin/env bash
#
# install-docker - Install Docker from the official apt repo.
#
set -euo pipefail

install-docker-prepare

sudo apt update &&
  sudo apt install \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin
