#!/usr/bin/env bash
#
# install-onlyoffice - Install OnlyOffice from the official apt repo
#
set -euo pipefail

install-onlyoffice-prepare

sudo apt update && sudo apt install onlyoffice-desktopeditors

install-onlyoffice-postinstall
