#!/usr/bin/env bash
#
# install-onlyoffice-prepare - Prepare to install OnlyOffice from the official apt repo.
#                              Does not perform the actual installation.
#
set -euo pipefail

mkdir -p ~/.gnupg
chmod 700 ~/.gnupg
gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
chmod 644 /tmp/onlyoffice.gpg
sudo chown root:root /tmp/onlyoffice.gpg
sudo mv /tmp/onlyoffice.gpg /usr/share/keyrings/onlyoffice.gpg

sudo tee /etc/apt/sources.list.d/onlyoffice.sources >/dev/null <<EOF
Types: deb
URIs: https://download.onlyoffice.com/repo/debian/
Suites: squeeze
Components: main
Signed-By: /usr/share/keyrings/onlyoffice.gpg
EOF
