#!/usr/bin/env bash
#
# install-firefox-prepare - Prepare to install Firefox from the Mozilla
#                           apt repo and block the snap version.
#                           Stop short of installing through apt.
#
set -euo pipefail

sudo snap remove firefox || true

sudo install -d -m 0755 /etc/apt/keyrings

wget -qO- https://packages.mozilla.org/apt/repo-signing-key.gpg |
  sudo tee /etc/apt/keyrings/packages.mozilla.org.asc >/dev/null

sudo tee /etc/apt/sources.list.d/mozilla.sources >/dev/null <<EOF
Types: deb
URIs: https://packages.mozilla.org/apt
Suites: mozilla
Components: main
Signed-By: /etc/apt/keyrings/packages.mozilla.org.asc
EOF

sudo tee /etc/apt/preferences.d/mozilla >/dev/null <<'EOF'
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
EOF
