#!/usr/bin/env bash

# Purge old kernel packages that aren't needed anymore

echoheader "Active Kernel"

uname -r

echoheader "Kernels to Purge"

mapfile -t packages < <(oldKernels)
echo "${packages[@]}"

echoheader "Purging Old Kernels"

sudo apt purge "${packages[@]}"
