#!/usr/bin/env bash

# Updates installed scripts from public repository.

SCRIPTS_GIT_DIR=~/UbuntuScriptsGit/
SCRIPTS_DIR=/usr/local/sbin/
SHARE_DIR=/usr/local/share/
GIT_REPO=https://github.com/aensley/UbuntuScripts.git

echosmallerheader () {
  echo
  echo -e "===== \033[34m\033[1m$1\033[m ====="
  echo
}

echosmallerheader 'Syncing Git Repo'
if [ -d ${SCRIPTS_GIT_DIR} ]; then
  git -C ${SCRIPTS_GIT_DIR} checkout -f --quiet
  git -C ${SCRIPTS_GIT_DIR} fetch --all --prune --tags --quiet
  git -C ${SCRIPTS_GIT_DIR} checkout origin/main --quiet
else
  git clone ${GIT_REPO} ${SCRIPTS_GIT_DIR}
fi

echosmallerheader 'Copying Script Files'
sudo rsync -qpt ${SCRIPTS_GIT_DIR}sbin/* ${SCRIPTS_DIR}
sudo rsync -qptr ${SCRIPTS_GIT_DIR}share/* ${SHARE_DIR}
sudo rsync -qpt ${SCRIPTS_GIT_DIR}etc/update-motd.d/* /etc/update-motd.d/
sudo chown root:root ${SCRIPTS_DIR}*
sudo chmod 755 ${SCRIPTS_DIR}*

echosmallerheader 'Finished!'
