#!/usr/bin/env bash

# Re-enable IPv6 and disable the Wireguard VPN

sudo wg-quick down wg0 && \
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 && \
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0 && \
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
