#!/usr/bin/env bash

# Disable IPv6 and enable the Wireguard VPN

sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 && \
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 && \
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1 && \
sudo wg-quick up wg0
