#!/usr/bin/env bash

echoheader "Zpool List" && \
sudo zpool list && \
echoheader "Zpool Status" && \
sudo zpool status && \
echoheader "I/O Status" && \
sudo zpool iostat -v && \
echoheader "Snapshot Status" && \
sudo zfs get usedbysnapshots -t filesystem && \
echo && \
sudo zfs list -t snapshot && \
echoheader "Compress Ratio" && \
sudo zfs get compressratio -t filesystem && \
echoheader "Arc" && \
sudo arcstat && \
echoheader "Memory" && \
sudo free -m
