#!/usr/bin/env bash

echoheader "Zpool List" && \
sudo zpool list && \
echoheader "Zpool Status" && \
sudo zpool status && \
echoheader "Compress Ratio" && \
sudo zfs get compressratio && \
echoheader "Arc" && \
sudo arcstat && \
echoheader "Memory" && \
sudo free -m
